[package]
name = "traits"
version = "0.1.0"
authors = ["Rust cookbook trait test by Davidkim <vder8282@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
